# Generated by Django 4.1.3 on 2022-12-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudopp', '0002_category_crud_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='cat',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
