# Generated by Django 4.1.3 on 2022-12-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudopp', '0003_alter_crud_cat_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crud',
            name='cat',
            field=models.CharField(max_length=30),
        ),
    ]
